BEGIN TRY
	BEGIN TRANSACTION
		UPDATE Products SET Price = 25 WHERE ID = 7
		UPDATE Orders SET OrderStatus = 'InProgress' WHERE ID = 1
		UPDATE Users SET Email = 'oana@a.com' WHERE ID = 1
		DELETE FROM Addresses WHERE ID = 3
		DELETE FROM ProductOrders WHERE ID = 40
	COMMIT TRANSACTION
END TRY

BEGIN CATCH
	ROLLBACK TRANSACTION
END CATCH
